#!/usr/bin/env bash
echo "txt编辑器"
sleep 0.1
if command -v nano &> /dev/#!/usr/bin/env bash
echo "txt编辑器"
sleep 0.1
if command -v nano &> /dev/null; then
    sleep 0.2
    echo "成功" > /dev/null
else
    sleep 0.2
    echo "error!"
    exit 1
fi
sleep 0.3
read -p "请输入文件路径（单次运行无法修改！（路径结尾一定要带/号！））" lujing

while true; do
    sleep 0.5
    sleep 1
    ls "$lujing"
    sleep 1
    read -p "请输入文件名 " wenjian
    sleep 0.3
    read -p "请输入模式|查看[0]|编辑[1]" moshi
    if [[ "$moshi" == "1" ]]; then
       nano "${lujing}${wenjian}.txt"
    fi
    if [[ "$moshi" == "0" ]]; then
       cat "${lujing}${wenjian}.txt"
       
    fi
   sleep 0.5
   read -p "是否清屏？0是1否" qingping
   if [[ "$qingping" == "0" ]]; then
       clear
   fi
   
   
   if [[ "$qingping" == "1" ]]; then
       sleep 0.5
   fi  
   
   echo "完成！"
    sleep 2
    
done
    
    
; then
    sleep 0.2
    echo "成功" > /dev/null
else
    sleep 0.2
    echo "error!"
fi
sleep 0.3
read -p "请输入文件路径（单次运行无法修改！（路径结尾一定要带/号！））" lujing

while true; do
    sleep 0.5
    sleep 1
    ls "$lujing"
    sleep 1
    read -p "请输入文件名 " wenjian
    sleep 0.3
    read -p "请输入模式|查看[0]|编辑[1]" moshi
    if [[ "$moshi" == "1" ]]; then
       nano "${lujing}${wenjian}.txt"
    fi
    if [[ "$moshi" == "0" ]]; then
       cat "${lujing}${wenjian}.txt"
       
    fi
   sleep 0.5
   read -p "是否清屏？0是1否" qingping
   if [[ "$qingping" == "0" ]]; then
       clear
   fi
   
   
   if [[ "$qingping" == "1" ]]; then
       sleep 0.5
   fi  
   
   echo "完成！"
    sleep 2
    
done